
// As generated by dts-bundle

declare module 'exposed-ambient' {
    export import internalAmbient = require("internal-ambient");
}

declare module 'internal-ambient' {
    export var someInternalNumber: number;
}
